const BAD_REQUEST_ERROR = 400;
const AUTHENTICATION_ERROR = 403;
const NOT_FOUND_ERROR = 404;
const INTERNAL_SERVER_ERROR = 500;
const CONFLICT_ERROR = 409;
const AUTHORIZATION_ERROR = 401;

module.exports = {
  BAD_REQUEST_ERROR,
  NOT_FOUND_ERROR,
  INTERNAL_SERVER_ERROR,
  AUTHENTICATION_ERROR,
  CONFLICT_ERROR,
  AUTHORIZATION_ERROR,
};
