const BAD_REQUEST_ERROR = 400;
const AUTHENTICATION_ERROR = 401;
const NOT_FOUND_ERROR = 404;
const SUCCESS = 200;
const CREATED = 201;
const INTERNAL_SERVER_ERROR = 500;

module.exports = {
  BAD_REQUEST_ERROR,
  NOT_FOUND_ERROR,
  SUCCESS,
  CREATED,
  INTERNAL_SERVER_ERROR,
  AUTHENTICATION_ERROR
};
